### ISSUE TITLE
Pause and Resume

### ISSUE THREAD

**Issue by yamifr07** [IonDen/ion.sound#13]
Hi, how can I pause sound and then resume it.

Regards

**Comment by bali33** [comment]
Hi,

Sorry to bump this issue - I can't find any function to resume all sounds that are playing. You can pause all sounds by calling ion.sound.pause() but didn't find out how to resume all ? I tried to call ion.sound.play() but as expected it didn't work - I tried to call again ion.sound.pause() same result.

I'm not js expert - I looked in the code but didn't find a function that seems to be able to do that. 

Is there a way to resume all sounds ?

Thank you

**Comment by IonDen** [comment]
Hello, now there is no way to resume all sounds with ion.sound API. You should do this manually.
But, this weekend, ion.sound 3.0 will be released. It will have support for play, pause, stop and resume for all sounds at once.

**Comment by bali33** [comment]
That's great news ! I can't wait for it :-)

**Comment by bali33** [comment]
Hi,

Is the v 3.0 still planed for today ?

Thank you

**Comment by IonDen** [comment]
Hello, January 27 - 28. Some optimizations delayed a release.

**Comment by IonDen** [comment]
Done in 3.0
