### ISSUE TITLE
Not run in firefox

### ISSUE THREAD

**Issue by nicka1711** [IonDen/ion.sound#18]
The plugin not run in firefox

**Comment by harpsicord86** [comment]
Hi there,

I'm afraid that this isn't solved.  I'm using your plugin for a clock timer that I'm developing.  It works perfect in Chrome but not in IE11 or FireFox.  Could you have a look when you've got a moment.

Thanks you :-)

**Comment by IonDen** [comment]
@harpsicord86, you should have another problem.
