### ISSUE TITLE
Sound playing in mobile Safari but not in fullscreen mode from the home screen (iPad)

### ISSUE THREAD

**Issue by jgonggrijp** [IonDen/ion.sound#20]
I'm using jQuery.ionSound version 1.3.0 on iOS 8.1.1, but the issue already existed in iOS 7.

When I visit my site using mobile Safari, everything is fine and sounds play normally. However, when I add my site to the home screen and visit it from there, sounds don't play.

This might be a hard restriction imposed by iOS (which I'd like to know for sure), but if it isn't, I hope you can fix it.

**Comment by IonDen** [comment]
Hello, friends. Please test new 3.0 version. Should be fixed.

**Comment by panvourtsis** [comment]
hi Guys,

i am facing a problem as well with version 3. It doesnt work on ipad, iphone although it does work on android and desktop. I am initialize it like this

ion.sound({
        sounds: [
            {name: "button-click-trimmed"},
            {name: "answer-click"},
            {name: "answer-correct"},
            {name: "answer-wrong"},
            {name: "answer-timeup"},
            {name: "intro-categories"},
            {name: "intro-questions"}
        ],

        path: "assets/audio/",
        preload: false,
        multiplay: true,
        volume: 0.9
        //ready_callback: myReadyCallback
    });

and call it like this


ion.sound.play("button-click-trimmed");


i also did a debug and it does run it without a problem but no sound

**Comment by IonDen** [comment]
@panvourtsis, hi. I will need a demo of your project, to check what is wrong. The plugin was fully tested on iOS devices with no problems.

**Comment by panvourtsis** [comment]
specifically i have the testing sound in both formats MP3 and AAC but still. There are some pages that after you visit these pages the sounds start working. 

About the project i don't want to share the url in public because it is under development. Can i share it to you in an private way?

**Comment by IonDen** [comment]
Write to my email

вторник, 9 июня 2015 г. пользователь Panagiotis Vourtsis написал:

> specifically i have the testing sound in both formats MP3 and AAC but
> still. There are some pages that after you visit these pages the sounds
> start working.
>
> About the project i don't want to share the url in public because it is
> under development. Can i share it to you in an private way?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IonDen/ion.sound/issues/20#issuecomment-110283384>.
>


-- 
*Denis Ineshin*
JavaScript developer | IonDen.com <http://ionden.com>
