### ISSUE TITLE
A couple features don't work

### ISSUE THREAD

**Issue by CaptSaltyJack** [IonDen/ion.sound#26]
On [this page](http://ionden.com/a/plugins/ion.sound/demo.html) , the playback example at the bottom does not work (Mac OS 10.9.5, Firefox 35.0.1, also Chrome didn't work either).

And on [this page](http://ionden.com/a/plugins/ion.sound/demo_advanced.html), audio sprites do not work.

**Comment by IonDen** [comment]
Hi, friend. Thanx! I forgot to upload sound files, while deploying yesterday(( Sorry!
Test now, all working.
