### ISSUE TITLE
Stop all sounds ?

### ISSUE THREAD

**Issue by Cybalt** [IonDen/ion.sound#30]
Hello,

First, thanks for ion.sound, it's great !
However, is it possible to stop all sounds ?

I tried ion.sound.stop(); but i don't know if it's still working, because i have this error : 
TypeError: undefined is not an object (evaluating 'this.streams[0].stop')

Any help ?

**Comment by IonDen** [comment]
Hello, maybe a bug. Try a demo page, also to double check.

**Comment by IonDen** [comment]
Fixed in 3.0.1
