### ISSUE TITLE
Feature: prev() next() methods

### ISSUE THREAD

**Issue by MarekMaras** [IonDen/ion.sound#32]
Would this be possible? I need it very badly! ;)

Like:
ion.sound.next(); for next song in queue
ion.sound.prev(); for previous song
ion.sound.next('track'); for next trackname

**Comment by IonDen** [comment]
Hi, i don't think that plugin will need this. Because it should be done outside.

See the example: http://jsfiddle.net/IonDen/b1btfamf/
