### ISSUE TITLE
iceweasel 31.5.0 not sound

### ISSUE THREAD

**Issue by nepster-web** [IonDen/ion.sound#33]
В браузере iceweasel 31.5.0 под debian 7 звуки не воспроизводятся.

**Comment by IonDen** [comment]
Привет, есть вероятность, что в системе просто отсутствуют нужные кодеки. Я вообще не в курсе про этот браузер, умеет ли он вообще Web Audio API или HTML5 аудио?

**Comment by nepster-web** [comment]
Это обычный фаерфокс, только с другой более свободной лицензией. Ну например музыка vk работает (хотя там флеш плеер, наверно не в счет), html5 видео со звуком. Ну в общем везде звук есть.  Драйвер: PulseAudio. 

Таже система, только из под хрома все работает.

**Comment by IonDen** [comment]
Привет, еще раз. Если есть возможность, проверьте эту страницу и напишите здесь результаты.
http://ionden.com/a/plugins/ion.sound/audio_test.html

**Comment by nepster-web** [comment]
Привет. Без проблем.  
Однако походу это проблема именно с моей стороны. Я тогда проверял, у меня с  данного браузера звук есть только с флеш плееров. 

Results:
Your browser supports the HTML5 audio element.

OGG
    audio/ogg : maybe
OGG
    audio/ogg; codecs="vorbis" : probably
MP3
    audio/mpeg : maybe
MP3
    audio/MPA : no
MP3
    audio/mpa-robust : no
AAC
    audio/MP4A-LATM : no
AAC
    audio/mp4 : maybe
AAC
    audio/mp4; codecs="mp4a.40.2" : probably
AAC
    audio/mp4; codecs="mp4a.40.5" : no
WAV
    audio/wav" : no
WAV
    audio/wav; codecs="1" : probably
PCM
    audio/webm : maybe
PCM
    audio/webm; codecs="vorbis" : probably

Web Audio API: yes

**Comment by IonDen** [comment]
Мда, в общем не знаю чем еще помочь вам.

**Comment by nepster-web** [comment]
в любом случае спасибо. Будет время потормошу разработчиков браузера =)

**Comment by IonDen** [comment]
Да не за что)

**Comment by nepster-web** [comment]
Разобрался в чем проблема. Наверно есть смысл отписать, вдруг кому-то пригодиться. 
Штука такая: я использую блютуз наушники, и первый раз при подключении мне нужно было для всех устройств пульс студии указывать вместо дефолтных колонок (которых нет) драйвер блютуз наушников. 

Дело в том, что html5 плагин не отображает до тех пор пока нет какого-либо воспроизведения звука с html5 плеера. Заметил такое поведение совершенно случайно, переключил драйвер и все работает.

**Comment by IonDen** [comment]
Супер, ну могу сказать что это супер мега редкая ситуёвина)
