### ISSUE TITLE
IOS 6.x safari doesn't play

### ISSUE THREAD

**Issue by micrem73** [IonDen/ion.sound#35]
Hi,
Safari on my iPhone 4 running IOS 6.1.3, doesn't sound neither basic nor advanced demo webpage sounds. Safari on mac does.
Any hints?

**Comment by IonDen** [comment]
Hello, this is very old safari. Please check this page: http://ionden.com/a/plugins/ion.sound/audio_test.html

**Comment by micrem73** [comment]
Hi, 
Thanks for the reply.
Here is the result. Any hope these "maybe" can help?

Results:
Yay! Your browser supports the HTML5 audio element.

OGG
audio/ogg : no
OGG
audio/ogg; codecs="vorbis" : no
MP3
audio/mpeg : maybe
MP3
audio/MPA : no
MP3
audio/mpa-robust : no
AAC
audio/MP4A-LATM : no
AAC
audio/mp4 : maybe
AAC
audio/mp4; codecs="mp4a.40.2" : probably
AAC
audio/mp4; codecs="mp4a.40.5" : probably
WAV
audio/wav" : no
WAV
audio/wav; codecs="1" : probably
PCM
audio/webm : no
PCM
audio/webm; codecs="vorbis" : no

---------------------
Michele.cremaschi@gmail.com

Il giorno 02/mag/2015, alle ore 18:08, Denis Ineshin <notifications@github.com> ha scritto:

**Comment by IonDen** [comment]
Hi, again. Please check again this test page. I added one new check.

**Comment by IonDen** [comment]
Hi, again. One more question, did you try to autoplay the sound on your app?

**Comment by micrem73** [comment]
hi,

no i didn't. I suspect it wouldn't play anyway.

On Mon, Jul 27, 2015 at 6:48 AM, Denis Ineshin <notifications@github.com>
wrote:

> Hi, again. One more question, did you try to autoplay the sound on your
> app?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IonDen/ion.sound/issues/35#issuecomment-125085528>.
>



-- 
_________________________________________________________________
Michele Cremaschi
http://michelecremaschi.it
ph. +39.320.2992681

**Comment by IonDen** [comment]
Hi, i updated plugin a little bit. Maybe you could check it again in ios 6?

**Comment by faughnn** [comment]
I threw this together today: http://www.neeel.ie/ion/

Apparently doesn't work on iOS on either safari or chrome browser. Works fine on android chrome. Any ideas?
