### ISSUE TITLE
Sound not working on IE or Firefox

### ISSUE THREAD

**Issue by harpsicord86** [IonDen/ion.sound#36]
Hi there,

I'm using your plugin for a clock time project and I think it's great!  Only trouble is that I'm testing it in IE and Firefox and no sounds are playing.  I know this has been logged already but just thought that I'd make you aware.

Many thanks!

**Comment by harpsicord86** [comment]
Ok, I've investigated the issue further and I think I've solved the issues with Firefox.  Unfortunately IE 11 doesn't seem to want to work and I don't know whether that's because of the QuickTime plugin installed.

**Comment by IonDen** [comment]
Hi. Please, maybe you can show some demo to check your layout?

**Comment by harpsicord86** [comment]
Hi Denis,

Sorry for the delay.  I've added a test user on our system so that you can have a look and see what you think.  Here is a link to one of the pages which I'm having issues with on IE11

https://medicine.keele.ac.uk/dev/timekeeper/Configure/Sound

To access the page use the username "tester" and testing as the password.

Thanks for taking a look

**Comment by harpsicord86** [comment]
Hi,

I've managed to implement a workaround to the IE problem but I have another question for you... I'me trying to implement your plugin on a mobile version of my timer site and I've come a cross something interesting. Basically, I need sounds to play in the background at certain times.  This works flawlessly within Android but not so much on iOS.  Yet, sounds are triggered and played if assigned to a button for example.  Does that mean that your plugin can only work being triggered in iOS?

**Comment by IonDen** [comment]
Hi, this is a device restriction. You need a user action to play media. No
method to override this on iOS. Maybe in new 9.x iOS they will get rid of
this.

2015-05-22 11:02 GMT+03:00 harpsicord86 <notifications@github.com>:

> Hi,
>
> I've managed to implement a workaround to the IE problem but I have
> another question for you... I'me trying to implement your plugin on a
> mobile version of my timer site and I've come a cross something
> interesting. Basically, I need sounds to play in the background at certain
> times. This works flawlessly within Android but not so much on iOS. Yet,
> sounds are triggered and played if assigned to a button for example. Does
> that mean that your plugin can only work being triggered in iOS?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IonDen/ion.sound/issues/36#issuecomment-104557655>.
>



-- 
*Denis Ineshin*
JavaScript developer | IonDen.com <http://ionden.com>
