### ISSUE TITLE
Feature: Disable/Enable sound

### ISSUE THREAD

**Issue by Lomaster** [IonDen/ion.sound#37]
Can you make feature like $.fx.off in jQuery (disable/enable all animations)?
It will be nice for game's setting like "sound on/off".

**Comment by IonDen** [comment]
You can do it with "destroy" method. Look at the destroy demo: http://ionden.com/a/plugins/ion.sound/demo_advanced.html

**Comment by Lomaster** [comment]
Destroy is a bad idea. If you want enable sound again then you will make object again. 2nd problem - you must recreate sound list again (spend time for initialize again).

**Comment by IonDen** [comment]
No, it can destroy exact sounds. And init exact sounds. Look at the demo,
all other sounds on the page are safe

понедельник, 18 мая 2015 г. пользователь Lomaster написал:

> Destroy is a bad idea. If you want enable sound again then you will make
> object again. 2nd problem - you must recreate sound list again (spend time
> for initialize again).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IonDen/ion.sound/issues/37#issuecomment-102932588>.
>


-- 
*Denis Ineshin*
JavaScript developer | IonDen.com <http://ionden.com>

**Comment by Lomaster** [comment]
Anyway it very simple to use 1 variable for enable/disable sound then destroy and init array of sounds. Is it really hard to make feature with .fx on/off? I can send to you my code for example (make pull request?) :)
