### ISSUE TITLE
Feature: Set master volume

### ISSUE THREAD

**Issue by Lomaster** [IonDen/ion.sound#38]
I can set master volume from start:
ion.sound({volume: 0.9});
but second call:
ion.sound({volume: 0.5});
doesn't work.
If i need change volume for all sounds, i have to use ion.sound.play(SoundName, { volume: Volume });
I have to make additional variables and functions for master volume configuring.

**Comment by IonDen** [comment]
Yes, it is in plans.

**Comment by IonDen** [comment]
Added in 3.0.1

**Comment by mumbaimerijaan** [comment]
For this coming in later, use
ion.sound.volume({volume: 0.5});
This is for setting master volume or volume of all sounds in ion.sound

Hope this helps someone
