### ISSUE TITLE
No sound in chrome

### ISSUE THREAD

**Issue by hecforce** [IonDen/ion.sound#39]
I have sound working in firefox and ie yet no sound is working in Chrome. There is an XMLHTTPREQUEST failed to load error for the sounds to be loaded. Yet as stated I have sound in Firefox and ie. The plugin website works in these browsers and in chrome as well. The file path has not changed for any on the sounds. This issue is on the desktop version of Chrome.

**Comment by IonDen** [comment]
Hi, it is almost impossible to predict you problem. Please show some demo with a bug.

**Comment by hecforce** [comment]
Apologies. Here is a link to the file:
http://hecforce.com/_area51/4git/index4git.html.  It works online but not offline you can download the files here: http://www.hecforce.com/_area51/4git/ionSoundChromeIssue.zip. Also here is the error I am getting offline: http://hecforce.com/_area51/4git/error.png.

![error](https://cloud.githubusercontent.com/assets/12487039/7692533/60a60a22-fd93-11e4-9b30-d1789f648a69.png)

**Comment by IonDen** [comment]
Ok it is clear. To work offline it also should be run on some simple local server. Like this: https://github.com/gruntjs/grunt-contrib-connect or https://www.apachefriends.org/ru/index.html

**Comment by hecforce** [comment]
OK but why does the above work in FireFox and ie without additional files? It looks like it has something to do with the XHR?

**Comment by IonDen** [comment]
Different browsers works differently with accessing files on local
machines. Server solves this problem

вторник, 19 мая 2015 г. пользователь hecforce написал:

> OK but why does the above work in FireFox and ie without additional files?
> It looks like it has something to do with the XHR?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IonDen/ion.sound/issues/39#issuecomment-103366268>.
>


-- 
*Denis Ineshin*
JavaScript developer | IonDen.com <http://ionden.com>
