### ISSUE TITLE
NS_ERROR_DOM_BAD_URI exception in firefox

### ISSUE THREAD

**Issue by shenglingshi** [IonDen/ion.sound#40]
when I test ion.sound file in local firefox browser,the browser happend exception ,NS_ERROR_DOM_BAD_URI: Access to restricted URI denied?How can i solve the problem?

**Comment by IonDen** [comment]
Hi, install same easy local server and run it there. Like this: https://github.com/GruntJS/grunt-contrib-connect or this: https://www.apachefriends.org/index.html

**Comment by simonbuehler** [comment]
is there a way to drop XMLHttpRequest and load a local file ? i encounter the same error and can't install a webserver in the environment needed
