### ISSUE TITLE
trigger click to play sound

### ISSUE THREAD

**Issue by sieghurt** [IonDen/ion.sound#43]
Hi,

I tried using jquery trigger click event to play the sound. The function is triggered but the sound doesn't play. Wonder whether you can help me with this?

Thanks.
ian

**Comment by IonDen** [comment]
Why you need to trigger "click"? Just call ion.sound.play(...);

**Comment by sieghurt** [comment]
Below is my code.
for some reason, it doesn't auto play when it is not included in the click event but the click event manage to play make it played once I actually click it. yet, using jquery trigger doesnt trigger it to autoplay. 


$(document).ready(function()
{
     ion.sound
     ({
	sounds:
        [
	  {
		alias: "s5",
		name: "billie_jean"
	   }
	],

	 path: "sounds/",
	 preload: true,
	 multiplay: true,
	 volume: 1
	});
			
	ion.sound.play("s5");

        var toPlay = function() 
	{
		ion.sound.play("s5");
		console.log('lalalala');
		for(var i = 1; i <= 10; i++)
		{
			var setVolume = volumeUp + (i*1/10);
			slowlyFadeIn(i, setVolume);
		}
	};
	$("#b01_play").on("touchstart click", toPlay);
});

**Comment by IonDen** [comment]
Hey, you are trying to autoplay music on some iPhone/iPad etc? If so, it won't. Mobile devices required direct user action to enable media. This is an official restriction. Read this for example: https://developer.apple.com/library/safari/documentation/AudioVideo/Conceptual/Using_HTML5_Audio_Video/Device-SpecificConsiderations/Device-SpecificConsiderations.html

**Comment by sieghurt** [comment]
nope. Its not. I run it on desktop with chrome as my browser.

**Comment by IonDen** [comment]
Hi, did you manage to find out what happens?

**Comment by IonDen** [comment]
It should be fixed now. It was problem with autoplay.
