### ISSUE TITLE
中文浏览器(chinese brower qq)

### ISSUE THREAD

**Issue by wklc2015** [IonDen/ion.sound#46]
是否支持中文浏览器，qq浏览器和微信打开呢？

http://test.lckun.com/ion.soundjs.bug/bug.html

我的测试机是中国魅族android 4.4.4
测试的浏览器有 chrome, qq, uc,

测试bug：在qq浏览器和微信中浏览，播放一部分就停止了，如果设置了循环播放，则只循环开始一段。

**Comment by IonDen** [comment]
Hello, please write in english.
