### ISSUE TITLE
Sound plays on mobile app muted

### ISSUE THREAD

**Issue by CoericK** [IonDen/ion.sound#48]
Hello guys as the title says im having issued, i added this library for a mobile web app that im working on, it works well but turns out that the sound is beign played even when the mobile is muted, or in vibartinon mode, im calling the sound via onclick event. How can i fix this? is there any way?

**Comment by IonDen** [comment]
Hi, i never thought about this situation. Let's pretend that it is a bug. In few days i will try to find some time and check how we can handle this situation.

**Comment by CoericK** [comment]
Thank you for your fast answer @IonDen, i will be waiting for news.

**Comment by IonDen** [comment]
Hi, just checked on my iPhones safari browser.
It seems to be working correctly, sounds are playing only if the silent mode is off.

Please provide more info about your testing environment.

**Comment by CoericK** [comment]
Im testing it on a Samsung Galaxy A5, Android 4.4.4. 
```
 ion.sound({
                sounds: [
                    {name: 'pop_hi'}
                ],

                // main config
                path: '/assets/audio/pop_hi/',
                preload: true,
                multiplay: true,
                volume: 1
            });

            var soundEveryButton = function () {
                ion.sound.play('pop_hi');
            };
````

**Comment by CoericK** [comment]
Every time a user click on a button i call soundEveryButton it works but it works even when silent mode is on

**Comment by IonDen** [comment]
Ok i will try on my Nexus. It has android 5.x.

**Comment by CoericK** [comment]
Hello @IonDen did u make the test?

**Comment by IonDen** [comment]
Hi @CoericK 
I made a test on Google Nexus 7 (Android 5.1.1) Latest Chrome Browser.
Everything seems to be ok. Sound volume is following device volume. I device is on zero volume, nothing to hear.

**Comment by ErickArroyo** [comment]
Hi @IonDen Then what could be making my app behave on that way? Maybe i need to upgrade my library?

**Comment by CoericK** [comment]
Hi @IonDen Then what could be making my app behave on that way? Maybe i need to upgrade my library?

**Comment by IonDen** [comment]
Sorry, but i have no more ideas.
