### ISSUE TITLE
[Question/Suggestion]  Sound src as attribute, not based on key-name.

### ISSUE THREAD

**Issue by damarev** [IonDen/ion.sound#51]
Would be possible to do something like:

```
ion.sound({
    sounds: [
        {name: "beer_can_opening", src:"sounds/4ULMLGD.mp3" },
        {name: "bell_ring", src:"sounds/8YYV3S98.mp3"}
    ],
    preload: true
});
```

Its also possible to disable the nocache param suffix?

**Comment by IonDen** [comment]
Hi, you can use alias:
```javascript
        {
            alias: "s1",
            name: "door_bump"
        },
```
Src is generating with 3 params: name, path, and extention (this could be differrent, depends on device). That's why i recomment to add mp3, ogg and acc files.

Now there is no option to disable no_cache option. But soon it will be. Here is the ticket: #52

**Comment by damarev** [comment]
I would suggest #52 nocache feature disabled by default; makes more sense to be enabled at server ("sound.mp3?nc=FILE_HASH")

**Comment by IonDen** [comment]
Hi, no, it should be enabled by default, like normal ajax requests.

**Comment by IonDen** [comment]
#52 is in progress
