### ISSUE TITLE
can't play within ready_callback 

### ISSUE THREAD

**Issue by jodinathan** [IonDen/ion.sound#55]
Hi,

I made a small change within the setBuffer to call ready_callback after the creation of the stream.
Also added an autoplay option.

thanks for the awesome plugin =]

<img width="810" alt="ion_sound_js_-_dev_fun4me" src="https://cloud.githubusercontent.com/assets/6199518/9317963/82324ea2-4515-11e5-8b9c-02314aa3ded1.png">

**Comment by IonDen** [comment]
Hi, please highlight you changes somehow, or make a pull request.
