### ISSUE TITLE
No sounds on Firefox 40 (Ubuntu)

### ISSUE THREAD

**Issue by gigi214** [IonDen/ion.sound#56]
Hi, I've tried your demo page, but no sound were played on Firefox 40.
In Chromium 44 it's perfect!

my O.S. is Ubuntu 14.04 with kernel 4.1.6.

I hope you can fix soon this issue, thanks.

**Comment by IonDen** [comment]
Hi, i heard about Ubuntu problem. I had a mail conversation with one developer, he also had no sounds in FF ubuntu. But he managed to solve this problem, by replasing some drivers or, something like that.
So, sorry, this is not a plugin problem. Maybe, for temp fix, try to use other media formats. Check one after another: "mp3", "ogg", "mp4", "aac", "wav".

**Comment by IonDen** [comment]
Hello, any news about that?

**Comment by gigi214** [comment]
Hello, I've tried now on Firefox (40) with your demo pages, and it seems to work fine, except with the sprite objects. I only updated my OS with the latest packages.
I didn't try with different kind of file audio. I'm sorry, in these days I haven't much free time.
