### ISSUE TITLE
Looping doesn't work on Chrome&Android

### ISSUE THREAD

**Issue by moody19871987** [IonDen/ion.sound#57]
I have a problem with looping the sound on mobile device (Samsung Galaxy Tab 3, the latest Chrome version, Android 4.2). The sound plays only once. On desktop browsers everything works fine.
Does ion.sound support looping in mobile browsers?

Regards
Kuba

**Comment by IonDen** [comment]
Hello, i tested it on my Google Nexus 7 with Android 5.x. Everything worked fine.

**Comment by moody19871987** [comment]
I work on Android 4.2. Maybe this is the problem. I'll check it on other devices.

**Comment by IonDen** [comment]
Maybe you can update to KitKat 4.4 at least and test there?
