### ISSUE TITLE
sound dont worked in opera 32.0.1948.69

### ISSUE THREAD

**Issue by invader82** [IonDen/ion.sound#61]
Logs:
Remote Address:IP:80
Request URL:http://cdn.domain.org/js/ion.sound/sounds/icq.mp3?1445183860226
Request Method:GET
Status Code:200 OK

error log is empty

**Comment by IonDen** [comment]
Hello, @invader82 , only in Opera? What system? Does this remote host return cross origin (CORS) header?

**Comment by invader82** [comment]
Do you speak russian ?

**Comment by invader82** [comment]
Вообщем кроссдоменность прописал в конфиге nginx.
С этим проблем нету. я добавил 1 свой файл mp3 на хроме,амиго,мобильный хром проверял звук работает. а вот именно с оперы не хочет. хотя файл подгружаеться.

**Comment by IonDen** [comment]
Попробуйте OGG файл.

**Comment by invader82** [comment]
Спасибо, Сделал как у вас сконвертировал в mp3,aac,ogg все 3 файла закинул на сервер.
