### ISSUE TITLE
Sound doesnt play after a call

### ISSUE THREAD

**Issue by pmoitech** [IonDen/ion.sound#62]
Hello, I have an app mobile and it is working fine with ion js, but in some cases when the mobiles got a call it happens that, after the call is finished, the sound doesnt play. Is there a way to re-load the driver or other way to fix the problem? thanks.

**Comment by IonDen** [comment]
Hello, never heard about this bug. Please tell me more. What device, what op. system. Did you tested on other devices?

**Comment by pmoitech** [comment]
Hi, yes, in Android 4.1, the sound goes fine until there is a call, but it is not always, 2 of 3 I would say.

**Comment by IonDen** [comment]
Tell me more about your app. Technology stack.

**Comment by pmoitech** [comment]
My app is a web service, i use jquery mobile and html5, in my app i need to verify each 8 secs if there is service connection to the network, so i send a get to my server and wait for the response, if ok i play a success beep that means the server is online and the app is working fine, and if not response frome server i play a failure beep that means something is wrong with either the network or the server, all this ocurr each 8 secs. After a call, the app doesnt play any more the sound, neither success of failure

**Comment by IonDen** [comment]
You do that in browser or use something like Phonegap?

**Comment by pmoitech** [comment]
i use phonegab only to get the device info, dont try in browser

**Comment by pmoitech** [comment]
is there a way to know the sounds is not playing and force them to play..?

**Comment by IonDen** [comment]
Ok, maybe check this: http://stackoverflow.com/questions/16923778/phonegap-html5-audio-does-not-resume-playback-after-incoming-phone-call-on-iphon

**Comment by IonDen** [comment]
There are some onEnded callbacks. Try to use them.

**Comment by pmoitech** [comment]
about the onEnded callbacks, can you send me the url?

**Comment by IonDen** [comment]
https://github.com/IonDen/ion.sound#general-settings
http://ionden.com/a/plugins/ion.sound/demo_advanced.html - Callbacks section

**Comment by pmoitech** [comment]
Thanks
