### ISSUE TITLE
XMLHttpRequest cannot load file

### ISSUE THREAD

**Issue by MusStudent** [IonDen/ion.sound#63]
Hello! I tried to use ion.sound and got an error with loading files. I download example zip form your site http://ionden.com/a/plugins/ion.sound/en.html and copy and paste code from example files but it not working!

* I got this error in Google Crome 46.0.2490.80 m. 
* jQuery 1.11.3

> XMLHttpRequest cannot load file:///D:/Web/%D0%BE%D0%BD-%D0%BB%D0%B0%D0%B9%D0%BD%20%D0%B4%D0%B8%D0%BA%D…%82%D1%8B/2015%20%D0%B3%D0%BE%D0%B4/sounds/my_cool_sound.mp3?1446115717801. **Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.**

in 

>Sound.load	@	ion.sound.js:275
Sound.init	@	ion.sound.js:228
createSound	@	ion.sound.js:100
ion.sound	@	ion.sound.js:125
(anonymous function)	@	index.html:19

**Comment by IonDen** [comment]
Hi, ajax requests are not working on local computer. You should start any simpe server, like this:
https://github.com/gruntjs/grunt-contrib-connect
or this: https://www.apachefriends.org/ru/index.html

**Comment by MusStudent** [comment]
Thank you!
