### ISSUE TITLE
Autoplay bug

### ISSUE THREAD

**Issue by Andre-Rb** [IonDen/ion.sound#71]
I do hope this is a place to ask that kind of things :)
I had no success on stackoverflow, so if someone knows how to fix my issue it would be awesome !

http://stackoverflow.com/questions/34981443/cant-hear-any-sound-with-ion-sound-on-firefox-chrome

Thanks :)

**Comment by IonDen** [comment]
Hey, please describe your test environment.
Sounds are loaded via AJAX, so, you should have a running server on your local machine to play them. AJAX does not support file protocol.

**Comment by IonDen** [comment]
Found out that this was an autoplay bug. Fix will be ready soon.

**Comment by IonDen** [comment]
Fixed in 3.0.7
