### ISSUE TITLE
Aac format question

### ISSUE THREAD

**Issue by perrin4869** [IonDen/ion.sound#72]
Hi, I got an mp3 file I want to play, and I also want to provide ogg and aac alternatives as in the samples. I went ahead and used gulp-fluent-ffmpeg to automate conversion at runtime. Ogg file was obtained no problem, however, aac wasn't, and upon further research, it seems aac audio is usually found in mp4 or m4a containers. I couldn't find much information on aac containers. The question is, how do you obtain an aac file compatible with ion-sound by using ffmpeg, or more specifically, gulp-fluent-ffmpeg.
Also, the Mozilla documentation says that aac is only supported in mp4 containers. If so, when exactly are aac files used in practice?

**Comment by IonDen** [comment]
Hi. The preferable container for AAC for ion.sound is mp4. So, feel free to use it.
AAC container i did got on this [online converter](https://cloudconvert.com/formats#audio), so, it is only an option.

**Comment by perrin4869** [comment]
got it, thanks!
